# Generated by Django 2.2 on 2019-05-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0003_socialusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='docType',
            field=models.SmallIntegerField(choices=[(0, 'ID'), (1, 'Passport'), (2, 'Licence'), (3, 'BusinessCard')], default=2),
        ),
    ]
