# Generated by Django 2.2 on 2019-04-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='title',
            field=models.CharField(default='other', max_length=255),
        ),
    ]
